include:
  - project: hpc/gitlab-pipelines
    file:
      - spack-build-components.gitlab-ci.yml
      - github-project-pipelines.gitlab-ci.yml

stages:
    - .pre
    - build
    - test
    - build_neuron
    - test_neuron

# Set up Spack
spack_setup:
  extends: .spack_setup_ccache
  script:
    - !reference [.spack_setup_ccache, script]
    # This allows us to use the CoreNEURON repository in regression tests of
    # the gitlab-pipelines repositories. The regression test pipeline triggers
    # *this* pipeline as a child, having pushed a modified branch to the GitLab
    # mirror of the CoreNEURON repository. We have to update the Spack recipe
    # to point at the GitLab mirror so the relevant commit (on the modified
    # branch) can be found.
    - if [[ "${CI_PIPELINE_SOURCE}" == "pipeline" ]]; then
    - cd $(spack location -p coreneuron)
    - sed -i -e 's#\(git\s*=\s\)"https://github.com/BlueBrain/CoreNeuron"#\1"git@bbpgitlab.epfl.ch:hpc/coreneuron.git"#' package.py
    - git diff
    - fi

.spack_intel:
  variables:
    SPACK_PACKAGE_COMPILER: intel
.spack_coreneuron:
  variables:
    SPACK_PACKAGE: coreneuron
    SPACK_PACKAGE_SPEC: +debug+tests~legacy-unit
.spack_neuron:
  variables:
    SPACK_PACKAGE: neuron
    SPACK_PACKAGE_REF: '' # Take the default branch
    SPACK_PACKAGE_SPEC: +coreneuron+debug+tests~legacy-unit

# CoreNEURON will be checked out for us by default
build:coreneuron:intel:
  extends:
    - .spack_build
    - .spack_coreneuron
    - .spack_intel

test:coreneuron:intel:
  extends:
    - .ctest
  needs: ["build:coreneuron:intel"]

build:neuron:intel:
  stage: build_neuron
  extends:
    - .spack_build
    - .spack_neuron
    - .spack_intel
  needs: ["build:coreneuron:intel"]

test:neuron:intel:
  stage: test_neuron
  before_script:
    - !reference [.ctest, before_script]
    # Wipe Slurm environment to try and keep mpiexec happy. It would be nice to avoid this.
    - unset $(env|awk -F= '/^SLURM_/ {if (match($1, "_(ACCOUNT|PARTITION)$")==0) print $1}')
  extends:
    - .ctest
  needs: ["build:neuron:intel"]
