include:
  - project: hpc/gitlab-pipelines
    file:
      - spack-build-components.gitlab-ci.yml
      - github-project-pipelines.gitlab-ci.yml
  - project: hpc/gitlab-upload-logs
    file: enable-upload.yml

variables:
  NEURON_BRANCH:
    description: Branch of NEURON to build against CoreNEURON (NEURON_COMMIT and NEURON_TAG also possible)
    value: master
  NMODL_BRANCH:
    description: Branch of NMODL to build CoreNEURON against (NMODL_COMMIT and NMODL_TAG also possible)
    value: master

# Set up Spack
spack_setup:
  extends: .spack_setup_ccache
  variables:
    # Enable fetching GitHub PR descriptions and parsing them to find out what
    # branches to build of other projects.
    PARSE_GITHUB_PR_DESCRIPTIONS: "true"

simulation_stack:
  stage: .pre
  # Take advantage of GitHub PR description parsing in the spack_setup job.
  needs: [spack_setup]
  variables:
    CORENEURON_BRANCH: $CI_COMMIT_BRANCH
    MODELS_COMMON_BRANCH: $MODELS_COMMON_BRANCH
    NEURON_BRANCH: $NEURON_BRANCH
    PYNEURODAMUS_BRANCH: $PYNEURODAMUS_BRANCH
    REPORTINGLIB_BRANCH: $REPORTINGLIB_BRANCH
    SPACK_BRANCH: $SPACK_BRANCH
    SYNAPSETOOL_BRANCH: $SYNAPSETOOL_BRANCH
  trigger:
    project: hpc/sim/blueconfigs
    # CoreNEURON CI status depends on the BlueConfigs CI status.
    strategy: depend

# Performance seems to be terrible when we get too many jobs on a single node.
.build:
  extends: [.spack_build]
  variables:
    bb5_ntasks: 2   # so we block 16 cores
    bb5_cpus_per_task: 8 # ninja -j {this}
    bb5_memory: 76G # ~16*384/80

.spack_intel:
  variables:
    SPACK_PACKAGE_COMPILER: intel
.spack_nvhpc:
  variables:
    SPACK_PACKAGE_COMPILER: nvhpc
.build_neuron:
  extends: [.build]
  timeout: two hours
  variables:
    bb5_duration: "2:00:00"
    SPACK_PACKAGE: neuron
    SPACK_PACKAGE_SPEC: +coreneuron+debug+tests~legacy-unit~rx3d model_tests=channel-benchmark,olfactory,tqperf-heavy
.gpu_node:
  variables:
    bb5_constraint: volta
.test_neuron:
  extends: [.ctest]
  variables:
    bb5_ntasks: 16
    bb5_memory: 76G # ~16*384/80

# Build NMODL once with GCC
build:nmodl:
  extends: [.build]
  variables:
    SPACK_PACKAGE: nmodl
    SPACK_PACKAGE_SPEC: ~legacy-unit
    SPACK_PACKAGE_COMPILER: gcc

# Build CoreNEURON
build:coreneuron:mod2c:nvhpc:acc:
  extends: [.build, .spack_nvhpc]
  variables:
    SPACK_PACKAGE: coreneuron
    # See https://github.com/BlueBrain/CoreNeuron/issues/518 re: build_type
    SPACK_PACKAGE_SPEC: +gpu+openmp+tests~legacy-unit build_type=RelWithDebInfo

.build_coreneuron_nmodl:
  extends: [.build]
  before_script:
    # NEURON depends on py-mpi4py, most of whose dependencies are pulled in by
    # nmodl%gcc, with the exception of MPI, which is pulled in by
    # coreneuron%{nvhpc,intel}. hpe-mpi is an external package anyway, so
    # setting its compiler is just changing how it is labelled in the
    # dependency graph and not changing which installation is used, but this
    # means that in the NEURON step an existing py-mpi4py%gcc can be used.
    # Otherwise a new py-mpi4py with hpe-mpi%{nvhpc,intel} will be built.
    # TODO: fix this more robustly so we don't have to play so many games.
    - SPACK_PACKAGE_DEPENDENCIES="${SPACK_PACKAGE_DEPENDENCIES}^hpe-mpi%gcc"
    - !reference [.spack_build, before_script]

build:coreneuron:nmodl:nvhpc:acc:
  extends: [.build_coreneuron_nmodl, .spack_nvhpc]
  variables:
    SPACK_PACKAGE: coreneuron
    # See https://github.com/BlueBrain/CoreNeuron/issues/518 re: build_type
    # Sympy + OpenMP target offload does not currently work with NVHPC
    SPACK_PACKAGE_SPEC: +nmodl~openmp+gpu+tests~legacy-unit+sympy build_type=RelWithDebInfo
  needs: ["build:nmodl"]

# Build NEURON
build:neuron:mod2c:nvhpc:acc:
  extends: [.build_neuron, .spack_nvhpc]
  needs: ["build:coreneuron:mod2c:nvhpc:acc"]

build:neuron:nmodl:nvhpc:acc:
  extends: [.build_neuron, .spack_nvhpc]
  needs: ["build:coreneuron:nmodl:nvhpc:acc"]

# Test NEURON
test:neuron:mod2c:nvhpc:acc:
  extends: [.test_neuron, .gpu_node]
  needs: ["build:neuron:mod2c:nvhpc:acc"]

test:neuron:nmodl:nvhpc:acc:
  extends: [.test_neuron, .gpu_node]
  needs: ["build:neuron:nmodl:nvhpc:acc"]
