include:
  - project: hpc/gitlab-pipelines
    file:
      - spack-build-components.gitlab-ci.yml
      - github-project-pipelines.gitlab-ci.yml

stages:
    - .pre
    - build
    - test
    - build_neuron
    - test_neuron

.spack_intel:
  variables:
    SPACK_PACKAGE_COMPILER: intel
.spack_nvhpc:
  variables:
    # We have to run GPU builds on GPU nodes for driver/makelocalrc reasons.
    bb5_constraint: volta
    SPACK_PACKAGE_COMPILER: nvhpc
.spack_neuron:
  variables:
    SPACK_PACKAGE: neuron
    SPACK_PACKAGE_REF: ''
    SPACK_PACKAGE_SPEC: +coreneuron+debug+tests~legacy-unit

emulate:neuron:gpu:
  stage: build
  extends:
    - .spack_neuron
    - .spack_nvhpc
  before_script: []
  script:
    - "/bin/curl --stderr - -s -f -r 0-0 'https://spack-llnl-mirror.s3-us-west-2.amazonaws.com/_source-cache/archive/23/236bdbdce46e6e6a3d61a337c0f8b763ca1e8717c03b369e87a7ec7ce1319c0a.tar.gz'"
