pipeline {
    agent {
        label 'bb5-full'
    }
    stages {
        stage('build') {
            steps {
                def build_type = Debug
                sh """
                    module load boost/1.68.0/serial intel/18.0.3 hpe-mpi/2.16 cmake/3.13.0

                    export CC=mpicc
                    export CXX=mpicxx

                    rm -rf build*
                    mkdir build_aos build_soa build_intel_aos build_intel_soa

                    cd $WORKSPACE/build_aos
                    echo "AoS build"
                    cmake  \
                      -G 'Unix Makefiles'  \
                      -DCMAKE_INSTALL_PREFIX=$WORKSPACE/install_aos/ \
                      -DCMAKE_BUILD_TYPE=$build_type  \
                      -DENABLE_SOA=OFF\
                      -DTEST_MPI_EXEC_BIN="mpirun" -DTEST_EXEC_PREFIX="mpirun;-n;2" -DAUTO_TEST_WITH_SLURM=OFF -DAUTO_TEST_WITH_MPIEXEC=OFF \
                      $WORKSPACE/
                    make VERBOSE=1 -j8

                    cd $WORKSPACE/build_soa
                    echo "SoA build"
                    cmake  \
                      -G 'Unix Makefiles'  \
                      -DCMAKE_INSTALL_PREFIX=$WORKSPACE/install_soa/ \
                      -DCMAKE_BUILD_TYPE=$build_type  \
                      -DTEST_MPI_EXEC_BIN="mpirun" -DTEST_EXEC_PREFIX="mpirun;-n;2" -DAUTO_TEST_WITH_SLURM=OFF -DAUTO_TEST_WITH_MPIEXEC=OFF \
                      $WORKSPACE/
                    make VERBOSE=1 -j8
                    """
            }
        }

        stage('test'){
            sh """
                module load hpe-mpi/2.16
                export MPI_UNBUFFERED_STDIO=1

                cd $WORKSPACE/build_aos
                echo "Testing AoS"
                ctest --output-on-failure -T test --no-compress-output -E cppcheck_test
                cd $WORKSPACE/build_soa
                echo "Testing SoA"
                ctest --output-on-failure -T test --no-compress-output -E cppcheck_test
                """
        }
    }
}
