name: clang-cmake-format-check
on:
    push:

jobs:
  build:
    name: clang-cmake-format-check
    runs-on: ubuntu-20.04
    steps:
        - name: Fetch repository
          uses: actions/checkout@v2
        - name: Install clang-format 11
          run:  sudo apt-get install clang-format-11 python3-pip
        - name: Install cmake-format 0.6.0
          run:  python3 -m pip install cmake-format==0.6.0
        - name: Configure
          shell: bash
          working-directory: ${{runner.workspace}}/CoreNeuron
          run: |
              export PATH=/home/runner/.local/bin:$PATH
              mkdir BUILD && cd BUILD
              cmake -DCORENRN_CLANG_FORMAT=ON -DCORENRN_CMAKE_FORMAT=ON -DCORENRN_ENABLE_MPI=OFF -DCORENRN_ENABLE_OPENMP=OFF -DClangFormat_EXECUTABLE=$(which clang-format-11) -DCMakeFormat_EXECUTABLE=$(which cmake-format) ..
        - name: Run clang-format
          shell: bash
          working-directory: ${{runner.workspace}}/CoreNeuron/BUILD
          run: make check-clang-format
        - name: Run cmake-format
          shell: bash
          working-directory: ${{runner.workspace}}/CoreNeuron/BUILD
          run: make check-cmake-format
