name: clang-cmake-format-check

concurrency:
  group: ${{ github.workflow }}#${{ github.ref }}
  cancel-in-progress: true

on:
    push:

jobs:
  build:
    name: clang-cmake-format-check
    runs-on: ubuntu-22.04
    steps:
        - name: Fetch repository
          uses: actions/checkout@v3
        - name: Install clang-format 11
          run: |
              sudo apt-get update
              sudo apt-get install clang-format-11 python3-pip
        - name: Install cmake-format 0.6.13
          run:  python3 -m pip install cmake-format==0.6.13
        - name: Run clang-format and cmake-format
          shell: bash
          working-directory: ${{runner.workspace}}/CoreNeuron
          run: CMake/hpc-coding-conventions/bin/format -v --dry-run
